services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=status-check-db
  app:
    build: ./app
    ports:
      - "8081:8081"
    depends_on:
      - api
      - db
    environment:
      - API_URL=http://api:8080
      - POSTGRES_URL=http://postgres:5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    privileged: true 
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:8080
  db:
    image: postgres:17.2
    container_name: postgres_container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "status-check-db"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data